services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: